import { Request, Response, NextFunction } from "express";
import { verifyCookieJwt } from "@seamless-auth/core";
import type { JwtPayload } from "jsonwebtoken";

/**
 * Express middleware that enforces authentication using Seamless Auth cookies.
 *
 * This guard verifies the signed access cookie generated by the Seamless Auth
 * server. If the access cookie is valid and unexpired, the decoded session
 * payload is attached to `req.user` and the request proceeds.
 *
 * If the access cookie is expired or missing *but* a valid refresh cookie is
 * present, the middleware automatically attempts a silent token refresh using
 * the Seamless Auth server. When successful, new session cookies are issued and
 * the request continues with an updated `req.user`.
 *
 * If neither the access token nor refresh token can validate the session,
 * the middleware returns a 401 Unauthorized error and prevents further
 * route execution.
 *
 * ### Responsibilities
 * - Validates the Seamless Auth session access cookie
 * - Attempts refresh-token–based session renewal when necessary
 * - Populates `req.user` with the verified session payload
 * - Handles all cookie rewriting during refresh flows
 * - Acts as a request-level authentication guard for API routes
 *
 * ### Cookie Parameters
 * - **cookieName** — Name of the access cookie that holds the signed session JWT
 * - **refreshCookieName** — Name of the refresh cookie used for silent token refresh
 * - **cookieDomain** — Domain or path value applied to issued cookies
 *
 * ### Example
 * ```ts
 * // Protect a route
 * app.get("/api/me", requireAuth(), (req, res) => {
 *   res.json({ user: req.user });
 * });
 *
 * // Custom cookie names (if your Seamless Auth server uses overrides)
 * app.use(
 *   "/internal",
 *   requireAuth("sa_access", "sa_refresh", "mycompany.com"),
 *   internalRouter
 * );
 * ```
 *
 * @param cookieName - The access cookie name. Defaults to `"seamless-access"`.
 * @param refreshCookieName - The refresh cookie name used for session rotation. Defaults to `"seamless-refresh"`.
 * @param cookieDomain - Domain or path used when rewriting cookies. Defaults to `"/"`.
 *
 * @returns An Express middleware function that enforces Seamless Auth
 *          authentication on incoming requests.
 */

export interface AuthenticatedRequest extends Request {
  user?: JwtPayload;
}

export interface RequireAuthOptions {
  cookieName?: string;
  cookieSecret: string;
}

/**
 * Express middleware that enforces authentication
 * using an already-issued Seamless Auth access cookie.
 *
 * NOTE:
 * - This middleware does NOT attempt token refresh.
 * - Refresh is handled upstream by ensureCookies().
 */
export function requireAuth(opts: RequireAuthOptions) {
  const { cookieName = "seamless-access", cookieSecret } = opts;

  if (!cookieSecret) {
    throw new Error("requireAuth: missing cookieSecret");
  }

  return function (
    req: AuthenticatedRequest,
    res: Response,
    next: NextFunction,
  ) {
    const token = req.cookies?.[cookieName];

    if (!token) {
      res.status(401).json({ error: "Missing access cookie" });
      return;
    }

    const payload = verifyCookieJwt(token, cookieSecret);

    if (!payload) {
      res.status(401).json({ error: "Invalid or expired access cookie" });
      return;
    }

    req.user = payload;
    next();
  };
}
